export {default as Navbar} from './navbar/Navbar';
export {default as Hero} from './hero/Hero';
export {default as About} from './about/About';
export {default as Featured} from './featured/Featured';
export {default as Services} from './services/Services';
export {default as Reviews} from './reviews/Reviews';
export {default as Team} from './team/Team';
export {default as Sponsors} from './sponsors/Sponsors';
export {default as Footer} from './footer/Footer'